# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_KakaoTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.4'

  # Pods for iOS_KakaoTalk

end
